// <auto-generated />
namespace WholesaleEnterprise.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class sales_migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(sales_migration));
        
        string IMigrationMetadata.Id
        {
            get { return "201610191549272_sales_migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
